In [48]:
# Initial imports
import os
import requests
import pandas as pd
from dotenv import load_dotenv
import datetime

%matplotlib inline

In [49]:
# Load .env environment variables
load_dotenv()

True

In [50]:
# Set Realtor API key 
api_key = os.getenv("RAPID_API_KEY")

In [51]:
url = "https://realtor.p.rapidapi.com/properties/v2/list-for-rent"

querystring = {"state_code":"CA","prop_type":"single_family,multi_family,condo","sort":"sold_date","offset":"0"}

headers = {
    'x-rapidapi-key': api_key,
    'x-rapidapi-host': "realtor.p.rapidapi.com"
    }

response = requests.request("GET", url, headers=headers, params=querystring)

In [65]:
# Convert JSON string to a dictionary
real_estate_data = response.json()

In [68]:
# Create Dataframe 
re_df = real_estate_data['properties']

real_estate_df = pd.json_normalize(re_df)[['prop_type', 'list_date','last_update', 'prop_status', 'year_built', 'address.city', 'address.county','address.postal_code','address.lat','address.lon','community.price_min', 'community.baths_min', 'community.beds_min', 'community.sqft_min']]
real_estate_df.to_csv('list_for_rent_data.csv')
real_estate_df

,prop_type,list_date,last_update,prop_status,year_built,address.city,address.county,address.postal_code,address.lat,address.lon,community.price_min,community.baths_min,community.beds_min,community.sqft_min
0,condo,2021-02-15T14:43:00.000Z,2021-02-15T14:55:14.73Z,for_rent,NaN,Hawthorne,Los Angeles,90250,33.915979,-118.374959,4400,3.5,3,2000.0
1,single_family,2021-02-15T16:43:00.000Z,2021-02-15T16:55:13.13Z,for_rent,NaN,Long Beach,Los Angeles,90802,33.766265,-118.171427,3000,2.0,3,1200.0
2,condo,2021-02-15T16:43:00.000Z,2021-02-15T16:55:13.13Z,for_rent,NaN,Los Angeles,Los Angeles,90035,34.060528,-118.380012,3495,2.0,2,1700.0
3,single_family,2021-01-18T16:43:00.000Z,2021-02-15T14:55:14.73Z,for_rent,NaN,Santa Monica,Los Angeles,90405,34.010947,-118.465836,2100,1.0,1,450.0
4,single_family,2021-02-15T14:43:00.000Z,2021-02-15T14:55:14.73Z,for_rent,NaN,Beverly Hills,Los Angeles,90210,34.070292,-118.408719,36000,5.5,5,6749.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,condo,NaN,2021-02-15T04:55:16.953Z,for_rent,NaN,Solana Beach,San Diego,92075,32.981099,-117.263569,4595,2.5,3,1547.0
196,condo,NaN,2021-02-15T04:55:16.953Z,for_rent,NaN,Los Angeles,Los Angeles,90034,34.020479,-118.409082,3100,2.0,2,1106.0
197,condo,NaN,2021-02-15T04:55:16.953Z,for_rent,NaN,Mission Viejo,Orange,92692,33.579019,-117.649602,2650,2.5,2,1236.0
198,single_family,NaN,2021-02-15T04:55:16.953Z,for_rent,NaN,Merced,Merced,95348,37.349213,-120.470133,1800,2.5,3,1512.0
199,condo,NaN,2021-02-15T04:55:16.953Z,for_rent,NaN,Redwood City,San Mateo,94061,37.476462,-122.229977,2999,1.0,2,800.0