In [58]:
# Initial imports
import os
import requests
import pandas as pd
from dotenv import load_dotenv
import datetime

%matplotlib inline

In [59]:
# Load .env environment variables
load_dotenv()

True

In [60]:
# Set Realtor API key 
api_key = os.getenv("RAPID_API_KEY")

In [63]:
url = "https://realtor.p.rapidapi.com/properties/v2/list-for-sale"

querystring = {"state_code":"CA","prop_type":"single_family,multi_family,condo","sort":"newest","offset":"0"}

headers = {
    'x-rapidapi-key': api_key,
    'x-rapidapi-host': "realtor.p.rapidapi.com"
    }

response = requests.request("GET", url, headers=headers, params=querystring)

In [70]:
# Convert JSON string to a dictionary
real_estate_data = response.json()

In [71]:
# Create Dataframe 
re_df = real_estate_data['properties']

real_estate_df = pd.json_normalize(re_df)[['prop_type','last_update', 'prop_status', 'address.city', 'address.county','address.postal_code','address.lat','address.lon','price']]
# real_estate_df.to_csv('list_for_sale_data.csv')
real_estate_df

,prop_type,last_update,prop_status,address.city,address.county,address.postal_code,address.lat,address.lon,price
0,condo,2021-02-15T17:12:37Z,for_sale,Bell,Los Angeles,90201,33.981169,-118.190082,49999.0
1,single_family,2021-02-15T17:12:37Z,for_sale,Orange,Orange,92867,33.799920,-117.831847,679000.0
2,condo,2021-02-15T17:12:37Z,for_sale,Hawaiian Gardens,Los Angeles,90716,33.828730,-118.069232,400000.0
3,single_family,2021-02-15T19:14:33Z,for_sale,Eureka,Humboldt,95501,40.784328,-124.175370,280000.0
4,condo,2021-02-15T17:12:19Z,for_sale,Woodland Hills,Los Angeles,91367,34.171479,-118.601322,349000.0
...,...,...,...,...,...,...,...,...,...
195,single_family,2021-02-15T14:21:41Z,for_sale,Atwater,Merced,95301,37.346620,-120.623501,395515.0
196,single_family,2021-02-15T14:25:12Z,for_sale,Atwater,Merced,95301,37.346880,-120.622956,451790.0
197,single_family,2021-02-15T14:21:58Z,for_sale,Sacramento,Sacramento,95823,38.483170,-121.428936,345000.0
198,single_family,2021-02-15T18:17:36Z,for_sale,Menifee,Riverside,92587,33.701749,-117.246351,348500.0
199,single_family,2021-02-15T15:03:37Z,for_sale,Daly City,San Mateo,94014,37.691284,-122.453448,998000.0